// export type ChatRole = "user" | "assistant";

// export interface RAGContextChunk {
//   id: string;
//   page: number | null;
//   score: number;
// }


// export interface ChatSession {
//   id: string;
//   title: string;
//   messageCount: number;
//   isClosed: boolean;
//   createdAt: string;
// }


// export interface ChatMessage {
//   id: string;
//   chatSessionId: string;
//   role: ChatRole;
//   content: string;
//   createdAt: string;

//   /** RAG context used by assistant (always array, default []) */
//   contextUsed: RAGContextChunk[];

//   /** Optional feedback (usually assistant only) */
//   userFeedback?: -1 | 0 | 1;
//   feedbackText?: string;
// }


// export interface UIChatMessage extends ChatMessage {
//   /** True while assistant is generating */
//   isTyping?: boolean;

//   /** True for optimistic messages not yet confirmed */
//   optimistic?: boolean;

//   /** Used for streaming updates */
//   streamId?: string;
// }


// export interface SendMessageRequest {
//   chatSessionId?: string; // undefined = new chat
//   content: string;
// }


// export interface SendMessageResponse {
//   chatSession: ChatSession;
//   userMessage: ChatMessage;
//   assistantMessage?: ChatMessage; // undefined if generation failed
// }


// 🔴 Updated TypeScript interfaces for RAG chatbot

/**
 * Each source from Pinecone DB that contributed to the answer -Used
 */
export interface ContextUsedItem {
  id: string;         // ID of the Pinecone vector / chunk
  score: number;      // Similarity score (0-1)
  page: number | null; // Optional page number from source
}

/**
 * The assistant content returned from LLM - Used
 */
export interface AssistantContent {
  answer: string;       // Short factual answer generated by LLM
  suggestions?: string[]; // Optional suggested follow-up questions
}

/**
 * The full result returned from answerWithHospitalContext - Used
 */
export interface AnswerWithContextResult {
  assistantContent: AssistantContent;  // LLM answer + suggestions
  contextUsed: ContextUsedItem[];      // Array of sources used
}

// Used
export type SearchHit = {
  _id: string;
  _score: number;
  fields?: {
    text?: string;
    page?: number;
  };
};

// Used
export type Namespace = {
  searchRecords: (args: {
    query: {
      topK: number;
      inputs: { text: string };
    };
    fields: string[];
  }) => Promise<{
    result?: {
      hits?: SearchHit[];
    };
  }>;
};


// Used 
export type AnswerWithContextParams = {
  content: string;
  namespace: Namespace;
  generateAnswer: (query: string, context: string) => Promise<{
    answer: string;
    suggestions?: string[];
  }>;
  topK?: number;
};
